# Generated by Django 5.2.3 on 2025-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
